### ISSUE TITLE
Error printing size_t value in log function.

### ISSUE THREAD

**Issue by ser90368141** [aws/ota-for-aws-iot-embedded-sdk#199]
I am building a library for **ESP32S2**.
I get the following errors during build:
**ota.c:1615:25: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]**
As I understood, size_t for ESP32S2 is unsigned int size. Whereas the log function uses unsigned long int.

A good solution would be to use casting for log functions, as is done in the coreMQTT library.
https://github.com/FreeRTOS/coreMQTT/blob/main/source/core_mqtt.c

An example of a log function from coreMQTT:
```
LogDebug (("BytesSent =% ld, BytesRemaining =% lu",
             (long int) bytesSent,
             (unsigned long) bytesRemaining));
```

**Comment by pvyawaha** [comment]
Hello, 

Thank you for reporting this , we are looking into fixing it.
