### ISSUE TITLE
Race condition and undefined behaviour in `OTA_Shutdown`

### ISSUE THREAD

**Issue by fhars** [aws/ota-for-aws-iot-embedded-sdk#219]
`OTA_Shutdown` contains this check at the top of the function:
```
    if( otaAgent.state == OtaAgentStateInit )
    {
        /* When in init state, the OTA state machine is not running yet. So directly set state to
         * stopped. */
        otaAgent.state = OtaAgentStateStopped;
    }
```
Since `OTA_Shutdown` is part of the public API, it may be called from any task, so there is no guarantee at all that the `OTA_EventProcessingTask` doesn't start executing somwhere else right after this check, setting `otaAgent.state` to `otaAgentStateReady`. 

Aditionally, since `otaAgent.state` is defined as a plain, non-atomic enum value, there is no guarantee at all that any changes to `otaAgent.state` made by the task executing `OTA_EventProcessingTask` are ever seen by code calling `OTA_Shutdown` from another task. A sufficiently smart compiler that understood FreeRTOS tasks and saw e.g. a device state management task that only ever called `OTA_Init`, `OTA_Suspend`, `OTA_Resume` and `OTA_Shutdown`  would be perfectly free to conclude that the only values `otaAgent.state` could ever have are `OtaAgentStateStopped` and `OtaAgentStateInit` and that the logic to actually send the shutdown event is dead code and inline an optimized version (which in that scenario without log messages would just be `otaAgent.state = OtaAgentStateStopped; return otaAgent.state;`) for that task.

**Comment by divekarshubham** [comment]
Thank you for bringing the issue to our attention, we are working on a timeline to incorporate this change into the library.
