### ISSUE TITLE
OTA_Resume starts the self-test timer without checking state.

### ISSUE THREAD

**Issue by jasonpcarroll** [aws/ota-for-aws-iot-embedded-sdk#421]
https://github.com/aws/ota-for-aws-iot-embedded-sdk/blob/0d3002cb62eb7ee7129fe255580827199d19559c/source/ota.c#L3434
OTA_Resume starts the self-test timer without checking the current state of OTA. If OTA is not in self-test mode, this timer will always go off and reset the device.

**Comment by ActoryOu** [comment]
Fixed with #439. I'm going to close the issue.

Thanks.
