### ISSUE TITLE
OTA in multiple device

### ISSUE THREAD

**Issue by git4gaurav** [aws/ota-for-aws-iot-embedded-sdk#437]
OTA for a single device is working. Please suggest how can I program multiple devices with one OTA job. Single binary file should be programmed in selected number of devices through OTA. Is this possible using Thing group? Please suggest.

Thanks

**Comment by n9wxu** [comment]
When you create the OTA job in the console you are given the choice to select your things, or select your thing group.  You can select multiple items in the list including a mix of things and thing groups.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/750641/169882356-610ddfbc-6a72-4c1d-a430-8d594284427d.png">

**Comment by ravibhagavandas** [comment]
Hope this clarifies your query. Please feel to open an issue if you have further questions.
