### ISSUE TITLE
[Enhancement] Unnecessary const char data. Bloated memory.

### ISSUE THREAD

**Issue by dachalco** [aws/ota-for-aws-iot-embedded-sdk#455]
**Is your feature request related to a problem? Please describe.**
[ota_mqtt.c#L111](https://github.com/aws/ota-for-aws-iot-embedded-sdk/blob/main/source/ota_mqtt.c#L111) is a waste of  space. You can go back and forth from numeric to ascii with the relation 
```
value_numeric = value_ascii - '0'`
```

**Describe the solution you'd like**
Less memory usage.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by n9wxu** [comment]
The simple table is usually smaller than the math and supports HEX (A-F) at no extra charge.
