### ISSUE TITLE
[BUG] Invalid topic used to publish request for outstanding OTA jobs

### ISSUE THREAD

**Issue by imoir** [aws/ota-for-aws-iot-embedded-sdk#480]
**Describe the bug**
This looks like a regression in commit e43672a0, the thing name is not added to the topic parts in function requestJob_Mqtt() in source/ota_mqtt.c.

**Host**
ESP32 with FreeRTOS/ESP-IDF

**To Reproduce**
Initialize the OTA agent, causing it to request outstanding OTA jobs, which will fail with AWS dropping the connection.

**Comment by paulbartell** [comment]
I opened PR #483 by cherry picking your original commit onto the main branch.
