### ISSUE TITLE
[BUG] OTA errors on startup if there are no outstanding OTA jobs

### ISSUE THREAD

**Issue by imoir** [aws/ota-for-aws-iot-embedded-sdk#482]
**Describe the bug**
On startup, when the OTA agent receives an empty OTA job message indicating that there are no OTA jobs outstanding, a couple of error messages are logged, hinting at a bad OTA agent state.

`E (7716) AWS_OTA: Failed to execute state transition handler: Handler returned error: OtaErr_t=OtaErrJobParserError`
`E (7746) AWS_OTA: Current State=[WaitingForJob], Event=[ReceivedJobDocument], New state=[CreatingFile]`

**Host**
ESP32 with FreeRTOS/ESP-IDF

**Additional context**
In source/ota.c, the function handleCustomJob() correctly detects that the job document is empty, but the structure of the code makes it difficult to treat this as an expected and valid condition.

**Comment by imoir** [comment]
Here is my rather unsatisfactory fix for for this issue : https://github.com/imoir/ota-for-aws-iot-embedded-sdk/commit/c7a33029fef56f9872d0c833489ad9be4863cc6a

**Comment by paulbartell** [comment]
@imoir Thanks for the bug report. We will look into it and your fix.

**Comment by kstribrnAmzn** [comment]
I'm going to close this as my PR was merged. Feel free to reopen if there is an issue.
