### ISSUE TITLE
[BUG] OTA_SetImageState() fails but still activates the image

### ISSUE THREAD

**Issue by BogdanTheGeek** [aws/ota-for-aws-iot-embedded-sdk#506]
**Describe the bug**
In `OTA_SetImageState()`, the device is first activated and then the job status is update. If the job update fails, the image is still active, the device will reboot with the new image, but the job will return FAILED.

**To Reproduce**
- Add delay in self test
- Disconnect from internet whilst in the self test

**Expected behavior**
The device reverts to the previous version or retries to update the job state.

**Comment by n9wxu** [comment]
No further development will be performed on this library.  See the readme.
